# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven


on: 
  workflow_dispatch:
    inputs:
      suite:
        description: 'Test suite'     
        required: true
        default: 'api'

jobs:
  build:

    runs-on: macOS

    steps:
    - uses: actions/checkout@v2
    - name: Build with Maven
      run: mvn clean test -Dsuite=${{ github.event.inputs.suite }}
