name: Java CI with Maven


on: 
  workflow_dispatch:
    inputs:
      suite:
        description: 'Test suite'     
        required: true
        default: 'api'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn clean test -Dsuite=${{ github.event.inputs.suite }}

